"""`vesuve`: one program, one pipeline per prize.

    vesuve formulas [--markdown]           the formulary: each equation, its fact, its source
    vesuve grand-prize   [options]         unroll automatically, and say how far
    vesuve progress      [options]         audit a published segment: where did it change winding?
    vesuve first-letters [options]         a 4 cm² area, rendered, inked, and its witnesses
    vesuve paris4-title  [options]         look for the title of Scroll 1 where the text ends
    vesuve demo [--data DIR]               the four of them, on the embedded data (and local data if given)
    vesuve read <folder|report.json>       read a report back: its requirements, its stages, where it stops

Examples:
    vesuve grand-prize                     replays the certificate of the embedded segment (≈ 10 s)
    vesuve grand-prize --read              reads from the bucket the bands the procedure asks for
    vesuve progress --output audit         the audit: where the published segment changes winding
    vesuve read outputs/grand-prize --json

Each pipeline writes `report.json` and `report.md` into its output folder, and exits with 0 when it went as far as
it can, 2 when it stopped (the reason is in the report), 1 on a usage error. The journal goes to standard error;
`VESUVE_LOG=DEBUG` makes it verbose.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from vesuve import __version__
from vesuve.journal import Journal


def _formulas(a) -> int:
    from vesuve.formulary import FORMULARY
    if a.markdown:
        sys.stdout.write(formulary_as_markdown())
        return 0
    for e in FORMULARY.values():
        print(f"[{e.id:>4}] {e.stage:<3} {e.name} ({e.fact})\n       {e.latex}\n       {e.statement}")
    return 0


def formulary_as_markdown() -> str:
    """The formulary rendered for GitHub, DERIVED from the code: `vesuve formulas --markdown > FORMULARY.md`.

    ⚠ Each equation goes in a ```math fence and never between `$$`: GitHub applies Markdown's backslash escapes
    inside `$$` before the math renderer sees it, so `\\{`, `\\#` and `\\!` lose their backslash, the median's
    braces vanish and `\\#\\{\\ell\\}` fails to render. A fence is left alone.
    """
    from vesuve.formulary import FORMULARY
    lines = ["# The formulary", "",
             "*Generated by `vesuve formulas --markdown` from `vesuve/formulary.py`: do not edit by hand.*", "",
             "Every equation the program applies, the pipeline stage where it serves, the LplVesuvius registry fact "
             "that carries it (`docs/rapports/REGISTRE_*.tsv` on the `experimental` branch), and what computes it. An "
             "equation marked **C core** is a function of `core/include/vesuve.h`, checked against the very function "
             "of the research producer; the others are procedure rules, in Python.", ""]
    stages = {"E2": "E2: the scale", "B": "B: the budget of a sheet trace", "E4": "E4: the lattice",
              "E5": "E5: the holes", "E6": "E6: the certificate", "E7": "E7: judging without ground truth",
              "TN": "TN: computing the next winding",
              "TR": "TR: making the step tables of the correction",
              "T": "T: correcting the transfer to the next winding",
              "TJ": "TJ: judging the produced winding by its text",
              "E8": "E8: the ink, the measuring rule"}
    for key, title in stages.items():
        es = [e for e in FORMULARY.values() if e.stage == key]
        if not es:
            continue
        lines += [f"## {title}", ""]
        for e in es:
            who = "C core" if e.compute is not None else "procedure rule"
            lines += [f"### [{e.id}] {e.name}", "", "```math", e.latex, "```", "", e.statement, "",
                      f"*Fact* `{e.fact}` · *source* {e.source} · **{who}**", ""]
    return "\n".join(lines)


def _grand_prize(a, journal) -> int:
    from vesuve.grand_prize.pipeline import run
    r = run(a.segment, Path(a.output), Path(a.cache), read=a.read, rounds=a.rounds, threads=a.threads,
            readings=[Path(x) for x in a.readings], judge=a.judge, ink=not a.no_ink, surface=not a.no_surface,
            render=a.render, render_rows=a.render_rows, keep_piles=a.keep_piles, table_workers=a.table_workers,
            read_prediction=a.read_prediction, ink_readings=Path(a.ink_readings) if a.ink_readings else None,
            journal=journal)
    return 2 if r.stopped else 0


def _progress(a, journal) -> int:
    from vesuve.progress.pipeline import run
    r = run(a.segment, Path(a.output), Path(a.cache), readings=[Path(x) for x in a.readings], judge=a.judge,
            journal=journal)
    return 2 if r.stopped else 0


def _first_letters(a, journal) -> int:
    from vesuve.first_letters.pipeline import run
    r = run(Path(a.layers), Path(a.surface), a.scroll, Path(a.output), side_mm=a.side_mm,
            model=Path(a.model) if a.model else None, ink_map=Path(a.ink_map) if a.ink_map else None,
            labels=Path(a.labels) if a.labels else None, journal=journal)
    return 2 if r.stopped else 0


def _paris4_title(a, journal) -> int:
    from vesuve.paris4_title.pipeline import run
    r = run(Path(a.ink_maps), Path(a.output), Path(a.cache), meshes=Path(a.meshes) if a.meshes else None,
            journal=journal)
    return 2 if r.stopped else 0


def _read(a) -> int:
    """Read back a report a pipeline wrote, recomputing nothing."""
    import json
    path = Path(a.report)
    path = path / "report.json" if path.is_dir() else path
    if not path.exists():
        print(f"error: no report at {path}; a pipeline writes `report.json` into its --output", file=sys.stderr)
        return 1
    d = json.loads(path.read_text())
    if a.json:
        summary = {"prize": d["prize"], "stop": d["stop"], "requirements": d["requirements"],
                   "stages": [{k: s.get(k) for k in ("id", "name", "state", "reason")} for s in d["stages"]]}
        print(json.dumps(summary, ensure_ascii=False, indent=1))
        return 0
    print(f"{d['prize']} — {d['software']}, core {d['core']}")
    if d["stop"]:
        print(f"stopped at {d['stop']['stage']}: {d['stop']['reason']}")
    for s in d["stages"]:
        print(f"  {s['id']:<18} {s['state']:<8} {s['name']}" + (f" — {s['reason']}" if s.get("reason") else ""))
    for x in d["requirements"]:
        print(f"  [{x['state']}] {x['requirement']}: {x['what_is_measured']}")
    return 0


def _demo(a, journal) -> int:
    from vesuve.demo import run
    return run(Path(a.output), Path(a.cache), journal, Path(a.data) if a.data else None)


def main(argv=None) -> int:
    p = argparse.ArgumentParser(prog="vesuve", description=__doc__.splitlines()[0],
                                formatter_class=argparse.RawDescriptionHelpFormatter, epilog=__doc__)
    p.add_argument("--version", action="version", version=f"vesuve {__version__}")
    sub = p.add_subparsers(dest="verb", required=True)

    what_it_does = {  # what each verb does to the world: what it reads, writes, and how long it takes
        "grand-prize": "Replays the certificate of the embedded segment, offline, in about ten seconds; reads from the "
                       "public bucket the ink map (2 MB) and the surface (55 MB), unless --no-ink and --no-surface; "
                       "with --read, reads the bands asked for (about 21 min for 24263 chunks at 16 threads). It "
                       "computes the transfer to the next winding from the embedded samples of the prediction; with "
                       "--read-prediction, it reads them again from the public prediction (1780 chunks, about "
                       "630 MB) along the normals of the published mesh (55 MB, read even with --no-surface). It "
                       "measures, from the two embedded meshes, the share of the segment where the judge of the text "
                       "can see the produced winding (a few seconds); with --ink-readings, it reads the published ink "
                       "map (2 MB, read even with --no-ink) and judges the text of the produced winding on the readings "
                       "of the folder (it does not run the ink model itself). With "
                       "--render, makes the step tables of the correction here: it needs vc_render_tifxyz, downloads "
                       "the raw scan one row of blocks at a time and renders two piles per block, which takes hours "
                       "and needs about 40 GB free under --cache. Writes into --output. Exits 0 at the end, 2 if it "
                       "stops (the reason is in the report).",
        "progress": "Replays the same certificate to name where the published segment changes winding; reads the ink "
                    "map from the bucket for the image. Writes into --output. Exits 0, or 2 if it stops.",
        "first-letters": "Reads a local layer stack and, if given, an ink map; infers with --model (torch, minutes). "
                         "Writes PNGs named after the mesh. Exits 0, or 2 if the scroll is not eligible.",
        "paris4-title": "Reads the ink maps of the PHercParis4 bands and their meshes, locally. Writes views of the "
                        "end of the text. Exits 0, or 2 if no band is found.",
        "demo": "Chains the four pipelines; without --data, First Letters and Paris 4 are skipped, saying so.",
        "read": "Reads a report back, recomputing nothing; --json for machine output on standard output.",
    }

    def verb(name: str, help_: str) -> argparse.ArgumentParser:
        """Every subcommand shows its defaults, and what it does to the world."""
        return sub.add_parser(name, help=help_, description=what_it_does.get(name, help_),
                              formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    f = verb("formulas", "the formulary")
    f.add_argument("--markdown", action="store_true", help="render it as Markdown (FORMULARY.md)")

    def common(q, output):
        q.add_argument("--output", default=output, help="output folder")
        q.add_argument("--cache", default="cache", help="cache of the chunks and of the bucket's files")

    g = verb("grand-prize", "unroll automatically, and say how far")
    g.add_argument("--segment", default="20230702185753", help="an embedded segment")
    g.add_argument("--read", action="store_true", help="read from the bucket the bands the procedure asks for")
    g.add_argument("--rounds", type=int, default=6, help="reading rounds at most")
    g.add_argument("--threads", type=int, default=16, help="simultaneous reads")
    g.add_argument("--readings", nargs="*", default=[], help="bands already read, in the layout of the chain")
    g.add_argument("--judge", type=int, default=0, help="judge N certified chunks read from the bucket")
    g.add_argument("--no-ink", action="store_true", help="do not overlay the published ink map")
    g.add_argument("--no-surface", action="store_true", help="do not write the certified surface (55 MB read)")
    g.add_argument("--read-prediction", action="store_true",
                   help="compute the transfer to the next winding from the public prediction m7 (about 630 MB, and the "
                        "mesh, 55 MB)")
    g.add_argument("--ink-readings", default=None, metavar="DIR",
                   help="judge the text of the produced winding on the ink readings of DIR: calibration.npy (the "
                        "calibration block read on the reference) and produced_<row>_<column>.npy for each of the six "
                        "blocks the coverage names, 2048 x 2048 arrays from scrollprize/ink_canonical_2um")
    g.add_argument("--render", action="store_true", help="make the step tables of the correction here (hours)")
    g.add_argument("--render-rows", type=int, default=None, help="with --render, stop after N rows of blocks")
    g.add_argument("--keep-piles", action="store_true", help="with --render, keep the rendered piles (237 MB each)")
    g.add_argument("--table-workers", type=int, default=2,
                   help="with --render, processes that read the step tables while the next rows render (0: none)")
    common(g, "outputs/grand-prize")

    q = verb("progress", "audit a published segment: where did it change winding?")
    q.add_argument("--segment", default="20230702185753")
    q.add_argument("--readings", nargs="*", default=[])
    q.add_argument("--judge", type=int, default=0)
    common(q, "outputs/progress")

    fl = verb("first-letters", "a 4 cm² area, rendered, inked, and its witnesses")
    fl.add_argument("--layers", required=True, help="a folder of NN.tif layers around a surface")
    fl.add_argument("--surface", required=True, help="the tifxyz of that surface")
    fl.add_argument("--scroll", required=True, help="the scroll, for eligibility and regime (PHerc1447…)")
    fl.add_argument("--side-mm", type=float, default=20.0, help="the side of the area, in mm")
    fl.add_argument("--model", default=None, help="the folder of the ink model (TimeSformer), optional")
    fl.add_argument("--ink-map", default=None, help="an ink map already inferred (.npy, logits), of the stack's shape")
    fl.add_argument("--labels", default=None, help="the model's training labels, for the overlap check")
    common(fl, "outputs/first-letters")

    t = verb("paris4-title", "look for the title of Scroll 1 where the text ends")
    t.add_argument("--ink-maps", required=True, help="the folder of the published PHercParis4 ink maps (wNNN-MMM)")
    t.add_argument("--meshes", default=None, help="the folder of the bands' meshes (one tifxyz per segment)")
    common(t, "outputs/paris4-title")

    d = verb("demo", "the four pipelines, on the embedded and local data")
    d.add_argument("--data", default=None, help="a folder organised as the data/ of the experimental branch (First Letters, Paris 4)")
    common(d, "outputs/demo")

    rd = verb("read", "read back a report a pipeline wrote")
    rd.add_argument("report", help="an output folder, or its report.json")
    rd.add_argument("--json", action="store_true", help="the summary as JSON, on standard output")

    a = p.parse_args(argv)
    if a.verb == "formulas":
        return _formulas(a)
    if a.verb == "read":
        return _read(a)
    journal = Journal()
    return {"grand-prize": _grand_prize, "progress": _progress, "first-letters": _first_letters,
            "paris4-title": _paris4_title, "demo": _demo}[a.verb](a, journal)


if __name__ == "__main__":
    raise SystemExit(main())
